services:
  - type: web
    name: public-diamond-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn diamond_price_bot:flask_app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
